-- Snowflake Setup Script for New Account
-- Run this in Snowflake UI: Worksheets → SQL Worksheet

-- 0. Use role with permissions
USE ROLE ACCOUNTADMIN;

-- 1. Create Warehouse
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- 2. Create Database
CREATE DATABASE IF NOT EXISTS JOB_SEARCH;

-- 3. Use the database
USE DATABASE JOB_SEARCH;

-- 4. Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS STAGING;

-- 5. Create RAW tables
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS JOBS (
    JOB_ID VARCHAR(500) PRIMARY KEY,
    TITLE VARCHAR(500),
    COMPANY VARCHAR(500),
    LOCATION VARCHAR(500),
    DESCRIPTION TEXT,
    URL VARCHAR(1000),
    POSTED_DATE VARCHAR(100),
    SALARY VARCHAR(200),
    SOURCE VARCHAR(100),
    SCRAPED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 6. Create MARTS tables
USE SCHEMA MARTS;

CREATE TABLE IF NOT EXISTS JOBS_ENRICHED (
    JOB_ID VARCHAR(500) PRIMARY KEY,
    TITLE VARCHAR(500),
    COMPANY VARCHAR(500),
    LOCATION VARCHAR(500),
    DESCRIPTION TEXT,
    URL VARCHAR(1000),
    POSTED_DATE VARCHAR(100),
    SALARY VARCHAR(200),
    SOURCE VARCHAR(100),
    SCRAPED_AT TIMESTAMP_NTZ,
    -- Enriched fields
    SALARY_MIN NUMBER(10,2),
    SALARY_MAX NUMBER(10,2),
    IS_REMOTE BOOLEAN,
    EXPERIENCE_LEVEL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS REFERRAL_PATHS (
    ID NUMBER AUTOINCREMENT PRIMARY KEY,
    COMPANY VARCHAR(500),
    TARGET_PERSON VARCHAR(500),
    TARGET_TITLE VARCHAR(500),
    CONNECTOR_NAME VARCHAR(500),
    CONNECTOR_RELATIONSHIP VARCHAR(500),
    CONNECTION_TIER NUMBER,
    NOTES TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 7. Create STAGING tables
USE SCHEMA STAGING;

CREATE TABLE IF NOT EXISTS JOBS_CLEANED (
    TYPE VARCHAR(50),
    COMPANY VARCHAR(500),
    TITLE VARCHAR(500),
    AREA VARCHAR(200),
    LOCATION VARCHAR(500),
    ADDRESS VARCHAR(1000),
    TRANSIT_DURATION VARCHAR(100),
    TRANSIT_ROUTES VARCHAR(500),
    TRANSIT_CHANGES NUMBER,
    COMMUTE_RATING VARCHAR(50),
    COMMUTE_SCORE NUMBER,
    GOOGLE_MAPS_LINK VARCHAR(1000),
    CAREER_URL VARCHAR(1000),
    LINKEDIN_SEARCH VARCHAR(1000),
    CONTACT_NAME VARCHAR(500),
    CONTACT_EMAIL VARCHAR(500),
    CLOSEST_METRO VARCHAR(500)
);

-- 8. Verify setup
SHOW WAREHOUSES;
SHOW DATABASES;
SHOW SCHEMAS IN DATABASE JOB_SEARCH;
SHOW TABLES IN SCHEMA JOB_SEARCH.RAW;
SHOW TABLES IN SCHEMA JOB_SEARCH.MARTS;
SHOW TABLES IN SCHEMA JOB_SEARCH.STAGING;
